weights: yolov5s.pt
cfg: yolov5/models/custom_yolov5.yaml
data: dataset/data.yaml
hyp: .\yolov5\data\hyps\hyp.scratch.yaml
epochs: 3
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 0
project: runs/train
entity: null
name: yolov5s_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
save_dir: runs\train\yolov5s_results
